language: node_js
node_js:
- '4.0'
- '9.0'
sudo: false
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: rsgdAJUGN9h57xOpxpI/bBRI23sYWbzMlWCw46FZMV8BZuolSfBciTj1tblcuRL03gwNoDrBeOJOJJ5TlqL671hDIQ1NlRPJ1FomRePWMIWFYz1RKnHd9aYLe+hcNudVF6cfpMVJGDtzhIJIOIXslJJ/+wAYluwlQrwB9SubfoU=
  file:
    - "syllable.js"
    - "syllable.min.js"
  on:
    tags: true
    node: '9.0'
